"""Add featured field to Product model

Revision ID: 2648eb721567
Revises: f01385a2d3ad
Create Date: 2025-02-10 14:12:13.244260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2648eb721567'
down_revision = 'f01385a2d3ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('android_metadata')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('android_metadata',
    sa.Column('locale', sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
