"""Add featured field to Product model

Revision ID: 2648eb721567
Revises: f01385a2d3ad
Create Date: 2025-02-10 14:12:13.244260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2648eb721567'
down_revision = 'f01385a2d3ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed operation: op.drop_table('android_metadata')
    # Only add the necessary operations for your 'Product' model update, if any.
    op.add_column('product', sa.Column('featured', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed the creation of 'android_metadata' table.
    op.drop_column('product', 'featured')
    # ### end Alembic commands ###