"""Replace year with brand in products

Revision ID: 8ffb6935a809
Revises: d4e57f04d19d
Create Date: 2025-02-12 14:34:43.205065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ffb6935a809'
down_revision = 'd4e57f04d19d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.String(length=120), nullable=False))
        batch_op.drop_column('year')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.INTEGER(), nullable=False))
        batch_op.drop_column('brand')

    # ### end Alembic commands ###
