"""Add popularity field to Product model

Revision ID: d4e57f04d19d
Revises: a48fe430aa19
Create Date: 2025-02-10 14:23:12.235352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e57f04d19d'
down_revision = 'a48fe430aa19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('popularity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('popularity')

    # ### end Alembic commands ###
